// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connect.proto

package phoenix_messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	WphID                string   `protobuf:"bytes,1,opt,name=WphID,proto3" json:"WphID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetWphID() string {
	if m != nil {
		return m.WphID
	}
	return ""
}

type HelloResponse struct {
	WphID                string   `protobuf:"bytes,1,opt,name=WphID,proto3" json:"WphID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetWphID() string {
	if m != nil {
		return m.WphID
	}
	return ""
}

type Coordinate struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=Lon,proto3" json:"Lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{2}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Coordinate) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type CoordinateResponse struct {
	Time                 int64    `protobuf:"varint,1,opt,name=Time,proto3" json:"Time,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,3,opt,name=Lon,proto3" json:"Lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoordinateResponse) Reset()         { *m = CoordinateResponse{} }
func (m *CoordinateResponse) String() string { return proto.CompactTextString(m) }
func (*CoordinateResponse) ProtoMessage()    {}
func (*CoordinateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_778b7e3040344da6, []int{3}
}

func (m *CoordinateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoordinateResponse.Unmarshal(m, b)
}
func (m *CoordinateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoordinateResponse.Marshal(b, m, deterministic)
}
func (m *CoordinateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoordinateResponse.Merge(m, src)
}
func (m *CoordinateResponse) XXX_Size() int {
	return xxx_messageInfo_CoordinateResponse.Size(m)
}
func (m *CoordinateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CoordinateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CoordinateResponse proto.InternalMessageInfo

func (m *CoordinateResponse) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *CoordinateResponse) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *CoordinateResponse) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "phoenix.messages.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "phoenix.messages.HelloResponse")
	proto.RegisterType((*Coordinate)(nil), "phoenix.messages.Coordinate")
	proto.RegisterType((*CoordinateResponse)(nil), "phoenix.messages.CoordinateResponse")
}

func init() { proto.RegisterFile("connect.proto", fileDescriptor_778b7e3040344da6) }

var fileDescriptor_778b7e3040344da6 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0xae, 0x15, 0x1d, 0x2c, 0x96, 0xc1, 0x43, 0x29, 0xa2, 0xb2, 0x54, 0xf0, 0x14,
	0x4a, 0xfd, 0x09, 0x0a, 0x56, 0xe8, 0xa1, 0x44, 0x41, 0xaf, 0x6b, 0x1c, 0x6c, 0xa0, 0x9d, 0x89,
	0x49, 0x14, 0x7f, 0xbe, 0x98, 0x6e, 0x5a, 0xb1, 0xac, 0xb7, 0xc9, 0x9b, 0xf7, 0xbe, 0xe4, 0x11,
	0xe8, 0x19, 0x61, 0x26, 0x13, 0x95, 0xf3, 0x12, 0x05, 0xfb, 0x6e, 0x21, 0xc4, 0xf6, 0x4b, 0xad,
	0x28, 0x84, 0xfa, 0x8d, 0x42, 0x35, 0x82, 0xa3, 0x29, 0x2d, 0x97, 0xa2, 0xe9, 0xfd, 0x83, 0x42,
	0xc4, 0x13, 0xe8, 0x3e, 0xb9, 0xc5, 0xfd, 0xed, 0xa0, 0xb8, 0x28, 0xae, 0x0e, 0xf5, 0xfa, 0x50,
	0x5d, 0x42, 0xaf, 0x71, 0x05, 0x27, 0x1c, 0xa8, 0xc5, 0x36, 0x06, 0xb8, 0x11, 0xf1, 0xaf, 0x96,
	0xeb, 0x48, 0xd8, 0x87, 0x72, 0x56, 0xc7, 0xe4, 0x28, 0xf4, 0xcf, 0x98, 0x14, 0xe1, 0x41, 0xa7,
	0x51, 0x84, 0xab, 0x19, 0xe0, 0x36, 0xb1, 0xa1, 0x23, 0xec, 0x3d, 0xda, 0x15, 0xa5, 0x68, 0xa9,
	0xd3, 0x9c, 0x69, 0x9d, 0x1d, 0x5a, 0xb9, 0xa1, 0x4d, 0x9e, 0x9b, 0x32, 0x0f, 0xe4, 0x3f, 0xad,
	0x21, 0x9c, 0x42, 0xf7, 0xce, 0x13, 0x45, 0x3c, 0x53, 0x7f, 0x8b, 0xab, 0xdf, 0xad, 0x87, 0xe7,
	0xad, 0xfb, 0xf5, 0x8b, 0x26, 0x06, 0x8e, 0xe7, 0x12, 0x6c, 0xb4, 0xc2, 0x19, 0x3e, 0x87, 0x83,
	0x2c, 0xe1, 0xe9, 0x6e, 0x7e, 0x5b, 0x6b, 0x38, 0xfa, 0x6f, 0x9b, 0xaf, 0x18, 0x17, 0x2f, 0xfb,
	0xe9, 0x93, 0xae, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x59, 0xea, 0x26, 0xd2, 0xb5, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	Greet(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Greet(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/phoenix.messages.HelloService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	Greet(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoenix.messages.HelloService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Greet(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phoenix.messages.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _HelloService_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connect.proto",
}

// PositionServiceClient is the client API for PositionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PositionServiceClient interface {
	Position(ctx context.Context, in *Coordinate, opts ...grpc.CallOption) (PositionService_PositionClient, error)
}

type positionServiceClient struct {
	cc *grpc.ClientConn
}

func NewPositionServiceClient(cc *grpc.ClientConn) PositionServiceClient {
	return &positionServiceClient{cc}
}

func (c *positionServiceClient) Position(ctx context.Context, in *Coordinate, opts ...grpc.CallOption) (PositionService_PositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PositionService_serviceDesc.Streams[0], "/phoenix.messages.PositionService/Position", opts...)
	if err != nil {
		return nil, err
	}
	x := &positionServicePositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PositionService_PositionClient interface {
	Recv() (*CoordinateResponse, error)
	grpc.ClientStream
}

type positionServicePositionClient struct {
	grpc.ClientStream
}

func (x *positionServicePositionClient) Recv() (*CoordinateResponse, error) {
	m := new(CoordinateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PositionServiceServer is the server API for PositionService service.
type PositionServiceServer interface {
	Position(*Coordinate, PositionService_PositionServer) error
}

func RegisterPositionServiceServer(s *grpc.Server, srv PositionServiceServer) {
	s.RegisterService(&_PositionService_serviceDesc, srv)
}

func _PositionService_Position_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Coordinate)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PositionServiceServer).Position(m, &positionServicePositionServer{stream})
}

type PositionService_PositionServer interface {
	Send(*CoordinateResponse) error
	grpc.ServerStream
}

type positionServicePositionServer struct {
	grpc.ServerStream
}

func (x *positionServicePositionServer) Send(m *CoordinateResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PositionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phoenix.messages.PositionService",
	HandlerType: (*PositionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Position",
			Handler:       _PositionService_Position_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "connect.proto",
}
